id: P75AE9BB7
initial_creation_type: ocr
source_metadata:
  volumes:
    832430e85f17453581461eb9bae4723f:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: དེ་བཞིན་གཤེགས་པ་བརྒྱད་ལ་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
